### ISSUE TITLE
looks like at least languages behaviour changed on hrinfo

### ISSUE THREAD

**Issue by teodorescuserban** [OCHA-DAP/cod-migration#78]
The dataset test 4546 worked fine a thousand times.  It looks like a lot of datasets are getting this... Not sure if only languages have this issue or other fields as well.

We need to check for this.

Now I get:

```
Start processing dataset with Node ID = 4546
Traceback (most recent call last):
  File "gospawn.py", line 138, in <module>
    main()
  File "gospawn.py", line 121, in main
    run_test_short(short_test_ids)
  File "gospawn.py", line 81, in run_test_short
    c.migrate(dataset_row)
  File "/home/serban/Enc/Projects/HDX/hdx-gospawn/cod.py", line 197, in migrate
    self.format_dataset()
  File "/home/serban/Enc/Projects/HDX/hdx-gospawn/cod.py", line 458, in format_dataset
    h['caveats'] += ' '.join([x.upper() for x in d['languages']])
TypeError: 'NoneType' object is not iterable
```

Reassign to me after tagging.

**Comment by teodorescuserban** [comment]
Fixed.
